insert into public.events (
  id,
  title,
  starts_at,
  ends_at,
  city,
  venue,
  address,
  lat,
  lng,
  category,
  duration_min,
  price_min,
  price_max,
  currency,
  tags_json,
  image,
  gallery_json,
  description,
  url,
  is_published
)
values (
  'db-evt-010',
  'УСАДЬБА ДУБРОВИЦЫ МУЗЕЙ, КОТОРОГО НЕТ',
  '2026-02-01T09:00:00+03:00'::timestamptz,
  null,
  'Подольск',
  'Маршрут по городу',
  'Московская область, Подольск',
  55.4317,
  37.5451,
  'walk',
  480,
  0,
  null,
  'RUB',
  '["маршрут","поездка","архитектура","история"]'::jsonb,
  '/events/podolsk/podolsk-01.jpg',
  '["/events/podolsk/podolsk-01.jpg","/events/podolsk/podolsk-02.jpg","/events/podolsk/podolsk-03.jpg","/events/podolsk/podolsk-04.jpg","/events/podolsk/podolsk-05.jpg","/events/podolsk/podolsk-06.jpg","/events/podolsk/podolsk-07.jpg"]'::jsonb,
  E'Подольск расположен всего в 43 км от Москвы — отличное направление для короткого путешествия на один день. Добраться можно двумя способами: на машине или общественным транспортом (метро + пригородный автобус). В дороге вы проведёте меньше двух часов.\n\nПервой точкой маршрута стоит выбрать усадьба Дубровицы — парковка на территории бесплатная. Здесь же находится знаменитая Церковь Иконы Богоматери Знамения, а после осмотра можно прогуляться по парку вдоль река Десна.\n\nЕсли останется время, загляните и в другие достопримечательности города:\n— Троицкий собор\n— усадьба Ивановское\n— музей-заповедник «Подолье»\n\nДля завтрака подойдёт кафе Здрасте. Если решите остаться в городе до вечера, отправляйтесь на обед или ужин в гастропространство Депо (на Комсомольской улице, 3) — здесь представлена кухня на любой вкус.',
  'https://dubrovitsi.ru/',
  true
)
on conflict (id) do update
set
  title = excluded.title,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  city = excluded.city,
  venue = excluded.venue,
  address = excluded.address,
  lat = excluded.lat,
  lng = excluded.lng,
  category = excluded.category,
  duration_min = excluded.duration_min,
  price_min = excluded.price_min,
  price_max = excluded.price_max,
  currency = excluded.currency,
  tags_json = excluded.tags_json,
  image = excluded.image,
  gallery_json = excluded.gallery_json,
  description = excluded.description,
  url = excluded.url,
  is_published = excluded.is_published;
